### ISSUE TITLE
Null pointer Exception

### ISSUE THREAD

**Issue by venkatesh-arch** [Lzgabel/camunda-bpmn-converter#2]
Recieving Null pointer exception when testing in postman 

java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONObject.getJSONObject(String)" because "object" is null
	at cn.lzgabel.camunda.BpmnBuilder.build(BpmnBuilder.java:36)
	at cn.lzgabel.camunda.BpmnBuilder.build(BpmnBuilder.java:28)
	at cn.lzgabel.camunda.controller.WorkflowController.deploy(WorkflowController.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by Lzgabel** [comment]
Hi @venkatesh-arch. Thank you for your feedback. Please provide the request parameters you used for testing.

**Comment by venkatesh-arch** [comment]
Hi Lzgabel/camunda-bpmn-converter,
I am attaching a screenshot & sample json for your reference.

Thanks and Regards,
venkatesh

**Comment by venkatesh-arch** [comment]
Hi @Lzgabel 
When testing with http://39.97.98.194/deploy , bpmn xml is getting generated , but same input with the gitcode throwing exception.Attached input for reference.
[sample-request-2.zip](https://github.com/Lzgabel/camunda-bpmn-converter/files/8417114/sample-request-2.zip)
![Screenshot 2022-04-05 153544](https://user-images.githubusercontent.com/85412673/161732109-31f69af3-8c7f-460e-af08-91e3cac821c2.png)
![Screenshot 2022-04-05 153625](https://user-images.githubusercontent.com/85412673/161732114-7b8399f4-c8ad-4a40-8b18-40bc900ca9f6.png)

**Comment by Lzgabel** [comment]
Hi @venkatesh-arch. Thank you for your feedback. Just a moment, let me check it out.🙇

---
At the same time, I need to tell you that this project is just a simple demo, which only provides developers with the idea of json format conversion. Of course, if you have good suggestions, you are welcome to mention the issue. I will take the time to support it. Thank you.
